### ISSUE TITLE
Test 3box.io on Opera mobile

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#114]
Does this also touch 3box.js?

**Comment by oznekenzo** [comment]
This is Android only at the moment

**Comment by michaelsena** [comment]
@dazuck can you help test this for us? Thanks!

**Comment by michaelsena** [comment]
@dazuck any luck?

**Comment by dazuck** [comment]
Yeah it's a grey screen on the version with crypto.

---
typed quickly with thumbs

**Comment by dazuck** [comment]
@oznekenzo is this story to get it working on Opera, or just do the test?

**Comment by oznekenzo** [comment]
This just to test - I'll make a new one to debug what's going on with Opera
