### ISSUE TITLE
Update way users provide feedback in the app

### ISSUE THREAD

**Issue by dazuck** [3box/3box-dapp#139]

**Comment by michaelsena** [comment]
Cool idea @dazuck, do you think that this replaces the report an issue link? Once the user clicks the "Send feedback" link, they can select the type of feedback they want to give: 
* Report an issue ❗
* Give your opinion 💬
* Send praise 🎉

**Comment by dazuck** [comment]
was going to leave the implementation to the product team @michaelsena  :). 

But I was thinking it would be a second button under "report an issue" for now. We could do a nested thing and probably should long-term but feels more complex. 

Another option that TMNT is using, among others -- https://www.hotjar.com/incoming-feedback?utm_source=client&utm_medium=incoming_feedback&utm_campaign=insights
cc @oznekenzo

**Comment by oznekenzo** [comment]
Looking at hotjar now and I think we don't have enough elements on the platform just yet for the kind of product they're offering but I do really like the idea of users suggesting features as most people now are developers and getting as much of their input now obviously would be a great thing

**Comment by michaelsena** [comment]
Cool, will pick up research on this later in the sprint, going to focus on some more near terms prios first

**Comment by michaelsena** [comment]
Currently to provide feedback, users have to dig into the menu. Not many people have been providing feedback. I was going to recommend that we change the location and build a simple 5-star system ourselves since it would be so lightweight, but after reviewing Hotjar and seeing everything they can do, I'b beginning to lean more towards that - given their privacy features do as intended.

**Comment by michaelsena** [comment]
Here's the 3box.io site code ~~


<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:1106980,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>

**Comment by michaelsena** [comment]
Let's test with this code before we deploy anything to master and see what info it captures from ourselves first.

**Comment by michaelsena** [comment]
@oznekenzo can we try including the script tag above on the /Profile page or the tag manager?

**Comment by oznekenzo** [comment]
Yup will do

**Comment by michaelsena** [comment]
@oznekenzo did this make it into any of the releases today?

**Comment by oznekenzo** [comment]
@michaelsena no - I'm doing it right now - can you show me the documentation, its not showing up -

Or is this not supposed to show up in the interface?

**Comment by michaelsena** [comment]
Try this: https://help.hotjar.com/hc/en-us/articles/115009336727

It is supposed to show up, but only on the /Profile page. Did you install it there?

**Comment by oznekenzo** [comment]
What should I be looking for to show up in the interface?  I might be missing something in the documentation but it seems like this is just something that happens in the background - I don't see anything in that code that's going to place something in the interface

**Comment by oznekenzo** [comment]
Maybe it requires more setup in the hotjar admin panel ?

**Comment by michaelsena** [comment]
we may have to debug live

**Comment by oznekenzo** [comment]
Ok I'll push to alpha - - ?

**Comment by michaelsena** [comment]
sounds good
