### ISSUE TITLE
Implement "Jobs" page on 3box.io

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#145]
# Description
This issue adds a Jobs page to the 3Box web domain, which will live at https://3box.io/jobs

# Changes Required

- [x] Add "Jobs" page

- [x] Add "Jobs" link to navbar

- [x] Add "Jobs" link to footer

- [x] Link jobs to notion postings

- [ ] Make sure team@3box.io works

# Design Spec
![3boxjobspage](https://user-images.githubusercontent.com/5216274/49058590-ab0d4580-f1d2-11e8-8a57-036401086e4a.png)

**Comment by michaelsena** [comment]
Two notes of feedback @oznekenzo!
- can we left align the JD buttons when in mobile view? (this will make it work with the left aligned text)
- the jobs@3box.io link is still mailto:team@... can we update it to jobs@3box.io in the background too?

**Comment by oznekenzo** [comment]
@michaelsena ah my mistake.

And yes - now implemented.
