### ISSUE TITLE
Fix UI Issues & Updates

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-dapp#150]
- [x] Feed is not in middle
- [x] Raise profile details div
- [x] Feed should be below Profile details
- [x] Favicon in Allow Access dialogue is fuzzy
- [x] Edit Profile form fields too grey
- [x] Long email/details don't format well
- [x] Extended values in feed
- [x] Remove vw from feed
- [ ] Profile details width should flex with page
- [x] Update Feed design
- [x] Update Access Modal text
- [x] Update lock icon

**Comment by oznekenzo** [comment]
Feed now centered
<img width="1594" alt="feedcentered" src="https://user-images.githubusercontent.com/8059373/48799104-4b93cf00-ecd4-11e8-9ac7-5563787af9d2.png">

**Comment by oznekenzo** [comment]
Favicon in Access dialogue at correct resolution
<img width="472" alt="faviconresolution" src="https://user-images.githubusercontent.com/8059373/48799189-7f6ef480-ecd4-11e8-9b18-84634f7eecb6.png">

**Comment by oznekenzo** [comment]
Raise profile details div to be above feed section (this will continue to evolve as more of the specced features are added)
<img width="1371" alt="screen shot 2018-11-20 at 3 45 30 pm" src="https://user-images.githubusercontent.com/8059373/48801816-59008780-ecdb-11e8-872c-6e4128958308.png">

**Comment by oznekenzo** [comment]
Change edit profile form field color to white as per Sketch designs
<img width="781" alt="screen shot 2018-11-20 at 3 52 02 pm" src="https://user-images.githubusercontent.com/8059373/48802137-4a66a000-ecdc-11e8-9c7c-a0e7426318e8.png">

**Comment by oznekenzo** [comment]
Handle extended profile details
<img width="331" alt="screen shot 2018-11-20 at 4 04 10 pm" src="https://user-images.githubusercontent.com/8059373/48802702-fbba0580-ecdd-11e8-9904-c330f49a6a90.png">

**Comment by oznekenzo** [comment]
Extended values running over
<img width="673" alt="screen shot 2018-11-20 at 4 09 02 pm" src="https://user-images.githubusercontent.com/8059373/48802969-a9c5af80-ecde-11e8-8512-168f7167a5a8.png">
<img width="349" alt="screen shot 2018-11-20 at 4 05 50 pm" src="https://user-images.githubusercontent.com/8059373/48802970-a9c5af80-ecde-11e8-9709-35378d835d00.png">

**Comment by oznekenzo** [comment]
@michaelsena Neither Facebook, Github, nor Twitter flex the widths of their profile details section - are we sure we want to try this out? Regarding the last remaining empty check box

**Comment by michaelsena** [comment]
Thanks for bringing that up, I think let's hold on this story until we can screenshare and I can communicate at a higher band. I think you're right and we might need to adjust behavior slightly @oznekenzo
