### ISSUE TITLE
Onboarding modal shown on first login even if I have a profile

### ISSUE THREAD

**Issue by oed** [3box/3box-dapp#154]
**Describe the bug**
If I have a profile but have never logged in using this browser/computer I will get the onboarding modals shown. My profile will also be empty until I reload the page.

**To Reproduce**
Steps to reproduce the behavior, describing for firefox but should be similar for chrome:
1. Make sure you have a profile
2. Clear the localstorage and local db data from your browser. In firefox open the storage tab in the console window, right click on all items in "Indexed DB" and press remove. Also right click on localstorage and select "Remove All".
<img width="1570" alt="screenshot 2018-11-22 at 13 12 38" src="https://user-images.githubusercontent.com/3909429/48902666-883d0300-ee59-11e8-9747-5b5d10ab4d3a.png">

3. Reload the page and you will be presented with the onboarding modal.
<img width="1652" alt="screenshot 2018-11-22 at 13 14 44" src="https://user-images.githubusercontent.com/3909429/48902747-d0f4bc00-ee59-11e8-8426-38c28904999b.png">

4. You will be directed to the fill out profile form.
<img width="1518" alt="screenshot 2018-11-22 at 13 15 04" src="https://user-images.githubusercontent.com/3909429/48902774-e4078c00-ee59-11e8-86ed-2d26c0fcf827.png">

5. Now if you go to profile without entering any info you will be presented with an empty profile.
<img width="1152" alt="screenshot 2018-11-22 at 13 15 08" src="https://user-images.githubusercontent.com/3909429/48902800-f84b8900-ee59-11e8-9446-4922683093d3.png">

6. If you reload the page you will see your profile again.
<img width="1179" alt="screenshot 2018-11-22 at 13 15 26" src="https://user-images.githubusercontent.com/3909429/48902809-039eb480-ee5a-11e8-870a-81578cb6b551.png">

**Expected behavior**
If it's the first login the dapp should wait until the `onSyncDone` event has been fired, and then check if there is already a profile. The profile in the dapp should also be updated once this event has been fired.

**Desktop (please complete the following information):**
 - OS: macos
 - Browser: firefox

**Comment by oed** [comment]
@oznekenzo if there is no data you need to wait for `onSyncDone` to be called. If there is no data in the 3box after that then we can show the onboarding modal etc.
What do you mean with the 3box-activity? If there is data there or not shouldn't affect whether the onboarding modal is shown or not, right?

**Comment by oznekenzo** [comment]
@oed If I'm not mistaken, it's possible for a user to have entered data into their 3Box, and then removed it, and have 3Box return no data, correct?  If so, that user shouldn't be shown the onboarding modal again - but this logic would trigger the on boarding modal.  Is the shape of the empty data returned after a user has put data then removed that data different from the starting empty state of the data?  For this reason, I chose to work with data sent from the 3box-activity activity library - even if a user's profile is empty, if the user has logs of ```put``` or ```del``` it means the user has used the platform before and doesn't need to be shown the on boarding process

**Comment by oed** [comment]
oh, but that isn't part of the 3box-activity library right? That's just `box.public.log` for example?

**Comment by oznekenzo** [comment]
Ah right, yes that is just box.public.log

**Comment by oznekenzo** [comment]
Ok - so the dapp loading process ```await```s for the first box object, but not for onSyncDone.  I can add a check for an update in ```box.public.log``` and ```box.private.log``` after the first pass that will turn off the on-boarding process caused by an empty box object in localstorage.  This would cause a rare but undesirable UX of the on-boarding modals presenting themselves when localstorage is empty but the master copy of the data in the cloud shows otherwise.  Either this trade-off, or we always wait for ```onSyncDone``` to decide whether to start the on-boarding process with a tiny delay in showing it.

**Comment by oed** [comment]
I think it's fine if there is a short delay in showing the on-boarding modal. 
cc @michaelsena

**Comment by oznekenzo** [comment]
Cool - will implement now

**Comment by oed** [comment]
Thanks @oznekenzo
