### ISSUE TITLE
Provide users with a unique and specific profile URL

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#16]
This will set the stage for us to be able to share profiles with this link.

**Comment by oed** [comment]
would be something like 3box.io/ethereum-address and/or 3box.io/muport:did and/or 3box.io/ens-name

**Comment by michaelsena** [comment]
We would need to create this view for another user looking at my profile. Will mock something up when this becomes more a focus.

**Comment by michaelsena** [comment]
Use Ethereum address, since that's what we have support for in getProfile
