### ISSUE TITLE
"Leave Without Saving Changes?" Modal

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-dapp#162]

**Comment by michaelsena** [comment]
@oznekenzo is this the modal that is supposed to appear when the user attempts to leave the edit page before saving edited details?

**Comment by oznekenzo** [comment]
Yep

**Comment by michaelsena** [comment]
Here's the mock:
<img width="738" alt="screen shot 2018-12-05 at 8 54 28 pm" src="https://user-images.githubusercontent.com/5216274/49556042-1be9e700-f8d0-11e8-95d1-a84f27d41cec.png">

**Comment by oznekenzo** [comment]
@michaelsena 
Twitter & Airbnb don't do this, surprisingly.  
Facebook does it - they're able to show a custom modal when a user hits a link anywhere on their page, and back & forward buttons.  When a user hits reload however, you see a generic browser level modal.  
Facebook's approach is the best we can do for this, I'm assuming.  Still looking into how it's done.

**Comment by oznekenzo** [comment]
<img width="465" alt="screen shot 2018-12-11 at 3 03 49 pm" src="https://user-images.githubusercontent.com/8059373/49826892-ffc5ca00-fd55-11e8-928c-909c485c03ed.png">
<img width="558" alt="screen shot 2018-12-11 at 3 04 09 pm" src="https://user-images.githubusercontent.com/8059373/49826908-081e0500-fd56-11e8-9a94-3207d5639947.png">

**Comment by oznekenzo** [comment]
@michaelsena 
The generic modal cannot show a custom image bc it's been used for scams as stated here:
https://stackoverflow.com/questions/37782104/javascript-onbeforeunload-not-showing-custom-message
<img width="681" alt="screen shot 2018-12-11 at 3 05 12 pm" src="https://user-images.githubusercontent.com/8059373/49826973-2f74d200-fd56-11e8-8f02-8a82d5b1dd5d.png">

**Comment by oznekenzo** [comment]
@michaelsena we are able to inject a custom message only on some browsers - have continued research, posted a stackoverflow question - still haven't found a solution.
Do you want to move forward with the browser dialogues or only implement if we can have a custom modal?

**Comment by michaelsena** [comment]
@oznekenzo will we have system modals on mobile (Coinbase, Status, etc) or will we need our own modals for that?

**Comment by oznekenzo** [comment]
If we implement browser dialogues (not custom modals), then system modals would be what renders for those wallets, most likely

**Comment by michaelsena** [comment]
I need more info, let’s discuss on sprint planning today. My concern is that the system dialog may confuse users because although we know they are leaving the page when they click the verify button, the user doesn’t know that and so when they see something that is telling them to reload page? They may be confused. @oznekenzo

**Comment by oznekenzo** [comment]
That reload dialogue only happens when a user tries to reload the page - sorry for the mix up.  
Yeah - let's discuss this over voice/video.
If we're worried about a user forgetting to save when he starts the verify flow, we can definitely inject a save interaction before we take the user on the rest of the Github flow - that will be easy.

Closing the browser and reloading the window, on the other hand, are happening at the browser level and so are harder to inject page-level interactions.
