### ISSUE TITLE
Change icon on modals from MM logo to Web3 Wallet icon

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-dapp#165]

**Comment by michaelsena** [comment]
@oznekenzo with web3connect, this story is no longer relevant, correct?

**Comment by oznekenzo** [comment]
Not relevant anymore, will close now

**Comment by oznekenzo** [comment]
@michaelsena I was wrong, there is a modal telling you to sign into your metamask, should now be any web3 wallet

**Comment by michaelsena** [comment]
Okay, added it back to this upcoming sprint

**Comment by michaelsena** [comment]
closing bc I accidentally converted into an epic, will recreate issue
