### ISSUE TITLE
Create testing environment for the website

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#167]
# Description
As a 3Box core team member, I need to test the new features being developed by @oznekenzo before they are deployed to production so that we can test them and maintain our commitment to quality.

* Write tests for essential parts of the dapp

**Comment by michaelsena** [comment]
@c-castillo have you accounted for this in your release planning doc? How does this thinking compare with your proposal?

**Comment by oznekenzo** [comment]
- [ ] decide whether to reproduce data for development environment
- [ ] learn from Cristobal how to roll back a change on develop & master via circleci
- [ ] unit tests
- [ ] integration tests
- [ ] end to end tests

**Comment by oznekenzo** [comment]
Splitting this issue into smaller ones

**Comment by michaelsena** [comment]
@oznekenzo I see this is in review, however there are still stories missing? What should we do with this? Have you written the other stories yet?
