### ISSUE TITLE
Bug when adding images with transparent background

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#172]
**Describe the bug**
When adding an image with a transparent background, I see the 3Box blue as the default background color. I would expect it to be white for maximum adaptability for user images.

**To Reproduce**
1. Go to edit profile screen
2. Add an image with a partly transparent background
3. Click save
4. See image with blue background

**Screenshots**
![Screen Shot 2018-11-27 at 10.16.02 PM.png](https://images.zenhubusercontent.com/5b1e6edb4b5806bc2bd704db/e891b688-13ef-4228-802d-f938ab1e2741)

**Comment by michaelsena** [comment]
now the edit page doesn't show blue, but the view profile only shows white. See attached: 
<img width="1680" alt="screen shot 2018-11-29 at 11 16 12 pm" src="https://user-images.githubusercontent.com/5216274/49268344-fd49a300-f42c-11e8-8d6f-290659cc989d.png">

**Comment by oznekenzo** [comment]
@michaelsena Can you tell me if you're still getting this error? If so, let's jump on a call and you can tell me the behavior - it's working for me
