### ISSUE TITLE
Display messagebar to user on "Profiles/Create Account" page

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#173]
# Description
As a user on the "Profiles" page, when I click on "Create Profile" button in the navbar, I should see the messagebar notification telling me to create an account below.

# Design Spec
![3boxmessagebar.png](https://images.zenhubusercontent.com/5b1e6edb4b5806bc2bd704db/cb5af9df-a29f-4f6c-a99e-4d384426922b)

**Comment by michaelsena** [comment]
Copy or the messagebar:

When on https://3box.io/create, when a user clicks "Profiles" they should see "Experience profiles by joining 3Box below."

When on https://3box.io/create, when a user clicks "Create Profile" they should see "Create your profile below."

--

Separately @oznekenzo we will still need to check on this page is the user has web3 enabled, otherwise we will have to show them the download metamask static banner message.

**Comment by michaelsena** [comment]
Woo! Getting close :) 
Okay so a few pieces of interaction feedback.
- The user should not automatically see the banner after arriving, which is the case now. They should only see the banner if they are on the profiles page and click Create Profile in the nav, or if they are on the Create Profile page and click Profiles. At that time, let's have the message bar slide down and slide back up from below the nav, not fade in and out.

**Comment by oznekenzo** [comment]
Ok - will update now.

**Comment by oznekenzo** [comment]
Pushed to develop the new behavior.  
One thing I'm trying to figure out right now is an elegant solution to the design when the browser window is short, which currently forces the form to go under the banner and nav bar.
