### ISSUE TITLE
Research flow to create gist

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#177]
See if we can autofill from a button

**Comment by oed** [comment]
Pretty sure this is not possible unfortunately. At least without doing an OAuth step with github (#159).

Others have been researching this before as well: https://github.com/keybase/keybase-issues/issues/401

**Comment by oed** [comment]
https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/
It does seem possible to do the oauth flow in the frontend, but it seems like using oauth like that is discouraged, since it could be a security vulnerability.

**Comment by michaelsena** [comment]
Just following up here, we have decided to proceed with the non-oauth implementation for security reasons. The tradeoff is a bit of user experience, but since it's a github verification anyway it will be a more technical crowd. 

When the user clicks verify, they will see a popup with instructions on how to copy and paste their DID into Github and save the gist.
