### ISSUE TITLE
Implement end-to-end github verification flow

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#178]
# Text copied by the user

### 3Box Profiles
3Box is a social profiles network for web3. This post links my 3Box profile to my Github account!

✅did:muport:fh47fnkew8dnmfn295mdY7K3GMnnbvd67DHGwui47d9sm4 ✅

Create your profile today to start building social connection and trust online. https://3box.io/

**Comment by michaelsena** [comment]
# Design
@oed and @oznekenzo: I took a swing at creating designs for our Github verification modal. This is what will appear after the user clicks verify. Thoughts?

<img width="650" alt="screen shot 2018-12-04 at 6 15 47 pm" src="https://user-images.githubusercontent.com/5216274/49479452-0ea9fb00-f7f1-11e8-847c-90bb34336193.png">

**Comment by michaelsena** [comment]
Open questions:
1. Does the user need to type in their Github, or can we just pull it from wherever the gist is posted?
2. What happens in the UI if there is a failure for some reason?
3. Will we allow users to verify more than one Github account? How can we prevent them from posting Gists to many different github accounts? I guess they're all valid verifications, but would we show them?
4. How do we save the data on the user's edit profile screen before they leave this browser window, because sometimes returning to previous windows on coinbase wallet and other platforms causes you to sign out?

cc @oznekenzo

**Comment by oznekenzo** [comment]
Looks good - I'm worried it might be a tad long potentially for some screens or windows that aren't extended

**Comment by michaelsena** [comment]
@oznekenzo we can make it horizontal for desktop, good idea.

Thinking about it, maybe it makes sense to have the third step display the user's Github verification once verified. See new screen~
<img width="595" alt="screen shot 2018-12-04 at 7 13 25 pm" src="https://user-images.githubusercontent.com/5216274/49481418-e1f9e180-f7f8-11e8-901a-d07120c7d310.png">

**Comment by michaelsena** [comment]
Something for desktop if the one above is too long
<img width="1023" alt="screen shot 2018-12-04 at 9 03 48 pm" src="https://user-images.githubusercontent.com/5216274/49485271-4a9c8a80-f808-11e8-8e85-f7363c86c5cd.png">

**Comment by oed** [comment]
This looks good, I'd like the text that is being copied to be visible though. Might be confusing otherwise. 
Btw, check the verification flow for keybase. This is my proof from there: https://gist.github.com/oed/0d5d8886e53a96c75bc876ffa1759334
The flow is similar to what you describe above :)

**Comment by michaelsena** [comment]
@oed updated with your comments
<img width="737" alt="screen shot 2018-12-05 at 7 58 51 am" src="https://user-images.githubusercontent.com/5216274/49515008-b233f380-f863-11e8-9bf0-d8cf402883d2.png">

**Comment by oznekenzo** [comment]
Add state to save previous edits made to profile before bouncing to verification flow

**Comment by oed** [comment]
@oznekenzo this is the general flow for the technical implementation:

1. user opens dialog
2. dapp fetches https://api.github.com/gists/public in the background (which contains a json array)
3. dapp loops though the contents of the array
4. for every entry in the array we get the raw url `const url = entry.files[Object.keys(entry.files)[0]].raw_url`
5. for every url do `box.verified.addGithub(url)`
6. if 5 is successful it returns the github username and we are done. If it's not continue with 4 until we tried all entries
7. When we have checked all entries without any positive result we go back to step 2 (which will now be updated with new entries). Continue until it's verified, or the user cancels.

**Comment by oznekenzo** [comment]
@oed sounds good - (2) "dapp fetches api" happens upon user clicking something or starts automatically?  Dapp needs the user to enter their github username?

**Comment by oed** [comment]
It happens when the dialog opens. The username is not needed. This api gives you all gist that are recently created by all users. `box.verified.addGithub(url)` will return the username

**Comment by oznekenzo** [comment]
@oed I see - so the user must be signed into their respective github account on github in order for this to work?  I will put a warning or copy making sure this is the case with the user.

**Comment by oznekenzo** [comment]
@oed, @michaelsena  - so if I'm understanding this correctly,
Step 1, four comments above, is actually several steps after the steps that prompt the user to create a gist with their DID?
The steps you outline, Oed, is what happens after a user hits "Verify"

**Comment by oed** [comment]
@oznekenzo yes they need to, but the api I linked will contain all new gists of all users.

**Comment by oed** [comment]
@oznekenzo There isn't a "Verify" button that the user can press afaik.

**Comment by oznekenzo** [comment]
@oed how/where are we generating the DID that's copied to their gist?

**Comment by oznekenzo** [comment]
When is that value SET ?

**Comment by oznekenzo** [comment]
The verification process is only going to work if this modal is up (the modal itself is housing the function that polls for github gists with the users DID)

Is this the behavior we want @michaelsena and if so we should say so in the modal somewhere

**Comment by oznekenzo** [comment]
@oed I'm seeing a lot more text in the gist you posted [here](https://gist.github.com/oed/0d5d8886e53a96c75bc876ffa1759334) Oed, that's not necessary for this flow?  Right now were just copying the DID to the clipboard

**Comment by oed** [comment]
yes, just the did for now unless @michaelsena has some input

**Comment by oznekenzo** [comment]
we should give a suggestion for what the gist file should be named and what file type it should be, even if it doesn't matter (or say that it doesn't matter)

**Comment by oznekenzo** [comment]
@michaelsena updated with new text

**Comment by oznekenzo** [comment]
@oed just a small thing but box.verified.addGithub(url) returns errors, couldnt it just return false? jw

**Comment by oznekenzo** [comment]
@oed does box.verified.addGithub(url) SET the github username that's returned if matched?

**Comment by oznekenzo** [comment]
```
{
"message": "API rate limit exceeded for 98.113.38.158. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
"documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

**Comment by oznekenzo** [comment]
@michaelsena @oed 
Given some of the unexpected conditions listed above, what do you think of this new flow:

1. User enters github username in edit profile field
2. "Verify" button becomes highlighted when texted is entered in field
3. User clicks "Verify"
4. Github verification modal appears
5. (Modal Step 1) User copies DID by clicking button in modal
6.a (Modal Step 2) User opens new tab in Github by clicking button in modal
6.b User pastes DID + message to Gist and saves as public
7. (Modal Step3) User clicks "Check Verification" button in modal
8. Loading animation appears in modal
9. Using the Github username entered in Step 1, make a GET request to github.com/users/:username/gists
10. Parse through returned data to find DID - if fails, show message "Not found", if successful, show success message / icon
