### ISSUE TITLE
Implement end-to-end twitter verification flow

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#179]
# Tweet Message

This tweet links my 3Box profile to my twitter account! 

✅INSERT DID ✅

Join web3's social profiles network by creating your account on 3box.io today. @3boxdb

**Comment by michaelsena** [comment]
@oed thoughts on the verification tweet copy shown above, how did you say the URL could look?

**Comment by oed** [comment]
It would be https://3box.io/profile/did:muport:Qmasdviuseriugvh

Should be `... creating your account on https://3box.io ...` right?

**Comment by michaelsena** [comment]
@oznekenzo yup you can post the same did as in the github verification flow inside of the message above

**Comment by oed** [comment]
@oznekenzo oh, right. Same as addGithub. I'll try to get a new version of the library out this weekend!
