### ISSUE TITLE
Allow users to verify their email address

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#18]
Can integrate a @mi-xu library for this probably?

**Comment by mi-xu** [comment]
Here is the email verification library: https://github.com/mi-xu/uport-verify-email

It issues an attestation to an mnid-based identity claiming an associated email address, so whoever consumes the attestation must also trust the issuer.

**Comment by michaelsena** [comment]
Closing as adding new stories related to email verification in the app
