### ISSUE TITLE
Feature: Add 'Collectibles' section to 3Box Profile

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#183]
# Description
As a Gitcoin user, I would like to see my Kudos collectibles in my 3Box profile amongst my other forms of identity and reputation so that I can build my collective reputation.

# Questions
* How would they be displayed?

# Path Forward
* Gitcoin it?!

# Design
I was thinking something like this:
<img width="1100" alt="screen shot 2018-12-02 at 2 03 11 am" src="https://user-images.githubusercontent.com/5216274/49336775-83551d80-f5d6-11e8-8d91-5b2f0c6b1e9e.png">

**Comment by michaelsena** [comment]
ping @owocki 😄thoughts here?

**Comment by oznekenzo** [comment]
This will be fun

**Comment by owocki** [comment]
love it

**Comment by michaelsena** [comment]
I think this will be useful for grabbing many of the most popular niftys for each address. https://docs.opensea.io/reference#api-overview

**Comment by michaelsena** [comment]
closing this issue, as I've opened a new one that is more considered. Now working on https://github.com/3box/3box-dapp/issues/194.
