### ISSUE TITLE
Allow users to verify their Github handle

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#19]
Can integrate a @mi-xu library for this probably?

**Comment by mi-xu** [comment]
The github and https identity linking dapp I prototyped a while back is here: https://github.com/mi-xu/ethense-linked-identity-dapp

It uses the legacy mnid and uport registry contract so establish and verify the links, so won't be directly useful for a muport-did implementation.

**Comment by michaelsena** [comment]
Closing this is an old duplicate
