### ISSUE TITLE
Debug Issue with Opera

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-dapp#190]
This will require me to go to the Equipment Room at NYU to test on an Android device

**Comment by michaelsena** [comment]
We will be working with @dazuck on Monday at ADO, you can likely use his phone then @oznekenzo

**Comment by oznekenzo** [comment]
From the Opera team:
```
Our team has verified and this is definitely a case of relying on web3 library injection.

`Uncaught TypeError: Cannot read property 'accounts' of undefined`

You need to include the library of your choice as part of your markup to resolve this issue.
```
Not sure why they are following a different paradigm from the other wallets, but will address this shortly

**Comment by oznekenzo** [comment]
@michaelsena This is going to take a rework of the web3 logic behind the dapp - and then careful testing as it could break in some edge cases that are being influenced by the code - when do we want to do this?

**Comment by oznekenzo** [comment]
Opera now working with web3connect
