### ISSUE TITLE
Implement profile page category menu

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#191]
# Description
As a user I want to be able to click though my profile in more digestible chunks, especially if we're going to be adding more profile categories.

note: this story is only for adding the sidebar to the Profiles page, there are separate stories for implementing the individual category pages.

# Requirements
Implement the following categories as separate subpages:
* `Activity`
* `Details`
* `Collectibles`

# Design
See categories on left with pages in middle
![Profile Page with Categories-Activity.png](https://images.zenhubusercontent.com/5b1e6edb4b5806bc2bd704db/95c6385d-410d-4628-aa36-fb7d21c3d5c2)

**Comment by oznekenzo** [comment]
@michaelsena do you want these categories to be separate routes? /profile/activity, /profile/details etc
Usually you want routes so that users can 1) bookmark them and 2) share direct links.  However if we're going to be sharing a different url, then only 1) applies.

**Comment by michaelsena** [comment]
Okay, I imagine we can optimize later. Ty @oznekenzo

**Comment by oznekenzo** [comment]
@michaelsena is separating the activity feed into 3box / ethereum / all in the scope of this issue?
Otherwise, this story is ready for review!

**Comment by oznekenzo** [comment]
<img width="1641" alt="screen shot 2019-01-09 at 11 19 03 am" src="https://user-images.githubusercontent.com/8059373/50912752-e0779680-1400-11e9-964a-7127c402456e.png">

**Comment by oznekenzo** [comment]
<img width="1640" alt="screen shot 2019-01-09 at 11 19 12 am" src="https://user-images.githubusercontent.com/8059373/50912761-e79ea480-1400-11e9-9830-3c0f6beda6a0.png">

**Comment by oznekenzo** [comment]
<img width="373" alt="screen shot 2019-01-09 at 11 19 42 am" src="https://user-images.githubusercontent.com/8059373/50912780-eff6df80-1400-11e9-91db-f849b9ba187d.png">

**Comment by oznekenzo** [comment]
<img width="384" alt="screen shot 2019-01-09 at 11 20 11 am" src="https://user-images.githubusercontent.com/8059373/50912799-f9804780-1400-11e9-9e1e-26414c4a02dc.png">

**Comment by michaelsena** [comment]
Looks good Kenzo, thanks!
