### ISSUE TITLE
Implement "👨‍🎤 Details" profile category page

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#193]
This is for implementing profile Details as its own page, referencing this issue: https://github.com/3box/3box-dapp/issues/191

# Design
Here is a rough design of the details page:
![Profile Page with Categories - Details.png](https://images.zenhubusercontent.com/5b1e6edb4b5806bc2bd704db/1c53fd64-ba5e-473c-b878-b311e9c130af)

**Comment by oznekenzo** [comment]
@michaelsena this is done and ready for review at the profileCategories branch.  Develop is a little backed up at the moment with all the verification stories, so can't push there.  Let me know if you want to jump on a call and we'll have you pull that branch so you can review it locally.  I could potentially push this to test.3box.io as well.  Just want to keep it separate from verifications until we know both are working well.  Let me know how you want to stage the releases w/ verifications + profile categories.
