### ISSUE TITLE
Implement "🏆 Collectibles" profile category page

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#194]

**Comment by oznekenzo** [comment]
- [ ] only show three last likes in the gallery view
- [ ] empty state in collectibles
- [ ] give credit to opensea (as per free api agreement)
- [x] asset contract.name + token id in description section
- [x] switch for padded collectible
- [x ] if padded, add background color if returned
- [ ]  add a semi transparent drop shadow
- [ ] art to be the full tile
- [ ] favorite / gallery section
- [ ] add to gallery function or drag and drop
