### ISSUE TITLE
Implement click-to-copy user URL microinteraction

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#196]
# Description
As a 3Box user, I need to copy my profile link so that I can share it on social media.

This occurs when the user clicks 'Share' on the profiles below. When clicked, I imagine the user sees a small micropopup that says "Profile URL copied".

Related to the Categories and View Profile story.

# Implementation
Implement the button on the following pages:
* Profile
* View Profile

# Design
Profile
![Profile Page with Categories-Activity.png](https://images.zenhubusercontent.com/5b1e6edb4b5806bc2bd704db/af2c1451-b711-4de3-b8ac-00ecbb5ece52)
View Profile
![Profile View Page.png](https://images.zenhubusercontent.com/5b1e6edb4b5806bc2bd704db/576ed2b9-3a2f-4a5f-9d93-d75a85ecdd38)

**Comment by michaelsena** [comment]
Check that on mobile it's not copying to clipboard. on Coinbase Wallet

**Comment by oznekenzo** [comment]
- [ ] moves window to bottom on copy
- [ ] copy function not working in mobile dapp browser
