### ISSUE TITLE
Implement expanded Collectibles view

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#197]
# Description
A user can click on the Collectible and see an expanded view.

# Detail
To close, user clicks anywhere besides on the collectible, or clicks "Close".

# Design Spec
![Screen Shot 2018-12-02 at 10.54.49 PM.png](https://images.zenhubusercontent.com/5b1e6edb4b5806bc2bd704db/32f4d4ae-2779-4401-bc09-b14ed43b42c4)

**Comment by michaelsena** [comment]
Under the main element, there will likely be another rectangular element that contains detail about the NFT that you can also get form the OpenSea API, such as attributes, or description, etc.

**Comment by oznekenzo** [comment]
- [ ] give credit to opensea (as per free api agreement)
