### ISSUE TITLE
Add footer social links and email signup

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#204]

**Comment by michaelsena** [comment]
@oznekenzo this is the slack email signup that we discussed yesterday for inspiration for our footer email signup. 
<img width="569" alt="screen shot 2018-12-06 at 8 39 24 am" src="https://user-images.githubusercontent.com/5216274/49587679-94818f80-f932-11e8-96ce-6a66791d91fb.png">

**Comment by oznekenzo** [comment]
<img width="467" alt="screen shot 2018-12-06 at 2 58 46 pm" src="https://user-images.githubusercontent.com/8059373/49608752-771ae880-f967-11e8-948b-3e25859891ec.png">

**Comment by michaelsena** [comment]
Much better! Let's try a few more tweaks, then good to go!
- remove the background on the input and button, leaving outlines
- change button to say "Subscribe"

**Comment by michaelsena** [comment]
Ah then nm, wouldn't worry about it, this looks good enough for now then! @oznekenzo
