### ISSUE TITLE
UI Tweaks

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-dapp#210]
- [x] update button font weight to 900 (font inside the buttons, not floating text)

- [x] update body font weight to 400

- [x] increase default line height to 1.2rems

- [x] Logo's font not rendering in SVG

**Comment by michaelsena** [comment]
There was a bug related to the svgs right @oznekenzo is that fixed?

**Comment by oznekenzo** [comment]
@michaelsena yeah it's fixed
