### ISSUE TITLE
Alert for attempting to save without verifying social field

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#212]
# Description
This is for users who enter their social accounts but don't verify them on the edit profile page, who them attempt to save their profile. We need to show them a warning. Basically it gives the user 2 options: 1) verify your profile, 2) remove your username from the field.

# Design
![Screen Shot 2018-12-06 at 12.59.25 PM.png](https://images.zenhubusercontent.com/5b1e6edb4b5806bc2bd704db/333dccb5-e194-4497-822b-e0c19c477adc)

**Comment by oznekenzo** [comment]
Require verification if entering username for Twitter & Github

**Comment by oznekenzo** [comment]
Like credit card form when you forget to add entry

**Comment by oznekenzo** [comment]
Show that verification hasn't happened
