### ISSUE TITLE
Put link to Medium publication in dapp footer

### ISSUE THREAD

**Issue by dazuck** [3box/3box-dapp#216]
Layout to be spec'd by Kenzo/Sena.

**Comment by michaelsena** [comment]
Thanks @dazuck, great suggestion. @oznekenzo can we add the Medium icon to the social icons in the footer?

**Comment by oznekenzo** [comment]
Yeah definitely good idea.  Will do that today

**Comment by oznekenzo** [comment]
@dazuck added to footer on alpha and ready for your review

**Comment by michaelsena** [comment]
@oznekenzo one small edit: can we direct users to the publication, not the user?

Right now we link to https://medium.com/@3box. We should update that to https://medium.com/3box - and we need to remember to do it across all pages it appears. Thanks!

**Comment by oznekenzo** [comment]
@michaelsena - yep - updated now
