### ISSUE TITLE
Set up non-production 3Box.io URLs

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#218]
### Description
As a 3Box developer, I need URLs to interact with the dapp in a non-production environment for many reasons.

### 
* Alpha: used for internal development, iteration, and testing; development.3box.io
* Beta: user for external testing, ensuring device compatibility, etc before full release; beta.3box.io
* Redirect alpha.3box.io to 3box.io
* Make sure google isn't indexing all the sites, just prod - 3box.io

**Comment by michaelsena** [comment]
Turn off crawling for searches on the subs

**Comment by oznekenzo** [comment]
will make a new issue for it
