### ISSUE TITLE
UX bugs in windows dapp 

### ISSUE THREAD

**Issue by dazuck** [3box/3box-dapp#219]
I'm getting several bugs when using 3box.io in chrome/windows. 
1. When I first login with Metamask on Rinkeby, my previously saved data does not show up (all blank fields). When I switch to mainnet it does show up, and when i switch back to rinkeby it persists. 
2. Background image not showing up
3. Correct font not rendering
 @michaelsena any to add? 

![image.png](https://images.zenhubusercontent.com/5b2d0d16ec017908afbeb74d/b1799030-f887-48c1-b4dc-09b35e190262)

**Comment by oznekenzo** [comment]
@dazuck Joao sent me another screen shot of the issue @ 3
It's an issue with the svg rendering incorrectly, I'll look into it

**Comment by oznekenzo** [comment]
Stale - can reopen if necessary
