### ISSUE TITLE
Add image to 3box.io metadata

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-dapp#220]
There currently is no preview image for the dapp site

Optimize for: 
- [x] Twitter
- [x] Google
- [x] Github (?)
- [x] Facebook
- [x] Slack
- [x] Duckduckgo
...anything missing?

**Comment by oznekenzo** [comment]
@oed this is super cool!!  And perfect for this, thanks!
One tradeoff though - @michaelsena - this is a lot of work.  This does give us the ability for users to share a prerendered page of their own profile with the appropriate meta data - but we don't even have that yet.  I can get to work on this, but I think it might be more than we need at the moment.  Until we have a real need to show custom rendered and route specific meta data, I think we are best off having hard coded meta-info/data/preview.  What do you think @michaelsena @oed?

**Comment by michaelsena** [comment]
have you been able to test this now @oznekenzo ?

**Comment by oznekenzo** [comment]
@michaelsena just tested - its working now!

**Comment by oznekenzo** [comment]
Working on Twitter as well
