### ISSUE TITLE
URL specific unfurling for link preview

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-dapp#224]
- [x] set up react helmet
- [ ] lambda function redirect only bots to cache service
- [ ] setup prerender.io or similar

Currently we have hard coded a link preview for the dapp.

In the future when we have routes tied to users, we should have link previews that prerenders a users profile as it is displayed, with meta data that is specific to the user.

The link @oed provided that will help with this:
https://medium.com/bounties-network/how-to-get-server-side-rendering-benefits-unfurling-indexing-search-ability-without-building-cf09c53a408

**Comment by michaelsena** [comment]
@oznekenzo how much effort do you think this is? And would you know how to go about doing this?

It could be a cool feature to enable for when we release following in the dapp. I imaging users will tweet their profile URL and say "Follow me!" and it would be awesome if this tweet contained a preview of their specific profile, instead of our generic 3box.io landing page

**Comment by oznekenzo** [comment]
@michaelsena  Having the meta data display as text in the link preview is pretty trivial using React Helmet, but getting a custom image to render (a screen shot taken for all profiles dynamically) is work in a few infrastructure layers and will require a paid service (https://prerender.io/pricing recommended above). I haven't done it but can do it, could be as little as 3 as much as 6 days, need to look into it a some more

**Comment by oed** [comment]
We could also do something simple where if you link to a users profile you just get their profile picture as a preview.

**Comment by michaelsena** [comment]
Agreed with @oed, seems like the simplest option! 🥇

**Comment by michaelsena** [comment]
To recap, when a public profile URL is shared, we want to display:
**Image**: user's profile image
**Title**: <Name>
**Description**: 3Box Profile for 0x12345...

**Comment by oznekenzo** [comment]
Have been reading through different implementations that deal with Facebook OG, Twitter, Slack etc.  React Helmet, which would have been the simplest solution, won't work even for just dynamic strings for Facebook OG, as it never runs JS when it scrapes.  Seems only solution is to inject server side logic that'll prepare the meta tags for the FB, TW, Slack etc bots for each profile

**Comment by oznekenzo** [comment]
Closing because now duplicate: https://github.com/3box/3box-dapp/issues/424
