### ISSUE TITLE
Clean UI and code refactor

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#225]

**Comment by oznekenzo** [comment]
- [ ] Create Profile form better behavior for shorter browser windows 
- [ ] Larger, juicier buttons

**Comment by michaelsena** [comment]
@oznekenzo I tested the nav hover, can we not animate the line in, rather just show it or don't on hover? The line gradually appearing is imo just a little bit too distracting and shouldn't command attention on the site.

I agree with the hover state line, but would prefer to remove the animation in.

**Comment by oznekenzo** [comment]
ok - will remove the animation

**Comment by michaelsena** [comment]
@oznekenzo did all these updates just go out in the latest release? Can I move this to done?

**Comment by oznekenzo** [comment]
@michaelsena yep!
