### ISSUE TITLE
Allow user to set profile photo from images on feed

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#228]
# Description
As a user who saved my Gitcoin avatar to my 3Box profile, I want an easy way to make it my default profile image so that I can complete the journey.

I think we could allow a user to take direct action on items in the feed with a menu button. On images, this would include an option to "Make profile photo"

## Detail
On images, when clicked this options menu button would include an option to "Make profile photo". When the user click this they get a confirmation modal, which when approved triggers a box.public.set image and updates the profile image in view.

# Intent
This issue is important because it would deliver a better experience for our integration with Gitcoin, a friend.

**Comment by dazuck** [comment]
@michaelsena I had one thought on profile photos. We may want to encourage users to have a static "ID photo" field that is actually a good head-shot, either as their profile photo or in addition to. A time-stamped photo of yourself signed with your 3Box key is potentially a non-trivially powerful verification in the future. The way shops etc look at the photo on an ID today, if 3Box is to be flexible in how it does "identity" and useable in in-person situations, being able to quickly look up a 3Box's self-attested ID photo and see when it was created could be a good lightweight id check.

**Comment by oed** [comment]
Meh, I think we are putting the cart before the horse here. To both of your points.

**Comment by michaelsena** [comment]
Agreed with @oed, @dazuck. Let’s keep it open and flexible for now and address this later. We’re profiles, not IDs.

**Comment by dazuck** [comment]
Yep, fully agree that this is not for now. Was just a thought i had related to this listening to the flight attendants on my flight debate whether the passenger a few rows back sufficiently matched the manifest for their comfort :)
