### ISSUE TITLE
Improve dapp loading time at server level

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-dapp#229]
Server work @c-castillo  (thx!)

- [x] Enable Gzip compression https://gtmetrix.com/enable-gzip-compression.html https://kinsta.com/knowledgebase/enable-gzip-compression/

- [x] Use efficient cache policy on static assets https://developers.google.com/web/tools/lighthouse/audits/cache-policy

**Comment by c-castillo** [comment]
I ended up using a lambda function to auto set the expire header
