### ISSUE TITLE
Set up build process using webpack

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#238]
With standard configs

@zachferland to outline 3 options and we will decide how to proceed

**Comment by zachferland** [comment]
The the issue with the build was from the scrypt crypto lib. Seems to come up when your machine doesn't build the c lib and just defaults to the precompiled (same happens with web3). Just installing 'node-gyp' seemed to work for me, the build was then able to make the correct bindings. 

```
npm install -g node-gyp
```

@oznekenzo can you try doing this and see if it works for you? and if error lets confirm we get the same error, this just solves the error i was seeing, but not sure if i had the same original error as you

**Comment by zachferland** [comment]
So far kenzo confirms it works in a quick try. Closing for now, lib will be added as part of build in another story.

**Comment by oed** [comment]
@zachferland Do you mind adding this as a comment to the issue in 3box-js?

**Comment by zachferland** [comment]
@oed there is a related issue open already?

**Comment by oed** [comment]
I think it's this one: https://github.com/3box/3box-js/issues/110
