### ISSUE TITLE
Add support for Token and Contract Metadata library

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#247]
@michaelsena commented on [Mon Oct 08 2018](https://github.com/3box/3box-activity/issues/8)

It would be awesome if we could have displayed all this bounties activity as being related to bounties network in the 3Box dapp this past weekend at ETH SF. (See attached screenshot) In the MM library linked below, it's StandardBounties.

Implement the lib that is determined from research.

**Comment by michaelsena** [comment]
@oed so where are we landing on this. Basically it doesn't seem like Trust provides the ability to return contract metadata for dapps, only tokens. MetaMask has the correct structure, but I have subtle concerns about it not being well maintained and quite limited in dapps/tokens. Did you also mention Aragon had one? 

I'm leaning towards MetaMask's version and we can always add additional support for other libs in the future for more coverage as they become available. For example in the future, we could default to one lib and fallback to the other if nothing returns from the first lib.

Thoughts? @oznekenzo is going to begin implementing today

**Comment by oznekenzo** [comment]
@michaelsena could you point me to the specific MM library that does this?

**Comment by oznekenzo** [comment]
https://github.com/MetaMask/eth-contract-metadata
