### ISSUE TITLE
Research which token and contract metadata library to use

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#250]
### Description
As a user, I would like to see token images and contract names appear in my activity feed so that I can have a better user experience.

Which one to use?
- MetaMask
- Trust Wallet
-OpenZeppelin

**Comment by michaelsena** [comment]
Trust wallet seems to support like 4-5x more tokens and dapps than metamask. For those reasons, I'd say go with them. https://github.com/TrustWallet/tokens 

@oznekenzo let me know if it's clear how to use the lib.

**Comment by oed** [comment]
@michaelsena seems like the trustwallet lib only supports token images though?

**Comment by michaelsena** [comment]
@oed i don't believe that's true. I looked through and dapps seem to be in there as well. https://github.com/TrustWallet/tokens/tree/master/dapps

**Comment by oed** [comment]
Those are just png's named after dapps. Doesn't seem to be a way to go from contract address to token name.

**Comment by michaelsena** [comment]
How are they using these then? I was poking around their API file to see if there was any mapping in there. Possible from eth addr > filename ... https://github.com/TrustWallet/trust-api/tree/master/src

Could the list I linked above only be for dapps listed in the dappstore in their mobile wallet?

It would stink if we couldn't use it because there are so many on that list. 😏 
@oed

**Comment by oznekenzo** [comment]
@michaelsena did we decide to go with MMs?

**Comment by michaelsena** [comment]
I’d like to hear confirmation from @oed but it seems that way. I don’t think trusts will be super easy or useful to us since we can’t get metadata by contract address, only domain. (At least that’s where we landed as of this afternoon) @oznekenzo

**Comment by oznekenzo** [comment]
Got it - will get started on that first thing tomorrow - as well as getProfile for addresses in the feed

**Comment by oznekenzo** [comment]
Will be a good time to use the graphql api as well
