### ISSUE TITLE
Improve UI for "Share Profile" button

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#267]

**Comment by oznekenzo** [comment]
<img width="295" alt="screen shot 2019-01-22 at 5 14 45 pm" src="https://user-images.githubusercontent.com/8059373/51569038-3f112b80-1e69-11e9-9f08-a27701dabb13.png">

**Comment by oznekenzo** [comment]
<img width="374" alt="screen shot 2019-01-22 at 5 14 34 pm" src="https://user-images.githubusercontent.com/8059373/51569043-43d5df80-1e69-11e9-9a77-40dcc48adebf.png">
