### ISSUE TITLE
Dapp not working in imToken 2.0 & Opera

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#269]
### Description
Phillip reported to me in Twitter that 3box.io app doesn't work in imToken 2.0, probably because they're injecting web3 automatically.

### Details
![Screen Shot 2019-01-23 at 9.45.39 AM.png](https://images.zenhubusercontent.com/5b1e6edb4b5806bc2bd704db/f72fcd31-6fc8-4161-9d66-274086f6a616)
![Screen Shot 2019-01-23 at 9.45.56 AM.png](https://images.zenhubusercontent.com/5b1e6edb4b5806bc2bd704db/8ca02ca2-c78b-48ac-a440-fb1b66be9001)

**Comment by oznekenzo** [comment]
@michaelsena my guess is this is happening for the same reason Opera doesn't work

**Comment by michaelsena** [comment]
I think this is now stale?

**Comment by oznekenzo** [comment]
Agreed, closing
