### ISSUE TITLE
Link to Culture article from Jobs page

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#270]
This is the article: https://medium.com/3box/3box-culture-a-team-community-and-company-595004959b61

Need to still decide best way to add, will make a quick suggestion and post here when ready.

**Comment by oznekenzo** [comment]
@msena, this is on develop but its just a first pass.  
Wondering, do we want it in the top banner section or below the email at the very bottom?
I want to make it look like an embedded Medium link
