### ISSUE TITLE
User status not displaying in public profile view

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#277]
Right now on the public profile view, inside the status element, the status is not displaying. For example I have a status set, however on https://3box.io/0xa8ee0babe72cd9a80ae45dd74cd3eae7a82fd5d1 , nothing appears.

**Comment by oznekenzo** [comment]
I'll fix this right away

**Comment by michaelsena** [comment]
Yup, tried it and it worked. You can close this story

**Comment by oznekenzo** [comment]
@michaelsena thanks for catching!
