### ISSUE TITLE
Add "My Data" option to dropdown menu

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#295]

**Comment by oznekenzo** [comment]
@michaelsena I don't quite agree here.  Why are we adding "Data" _and_ "Profile" to the header, then leaving the Profile icon with its dropdown here?  I think we leave "Data" in the nav (and leave it out of the dropdown), and the Profile icon remains as the link in the nav for what it represents, a Profile.

**Comment by michaelsena** [comment]
@oznekenzo I'd prefer to have both in both the header and the dropdown for now. This may change over time, but if we have data in the nav and leave out profile users will default to being on their data page all the time and not their profile. And that's not the behavior we want. Pls put both on the nav and in the dropdown. Thanks
