### ISSUE TITLE
"Delete This Item?" Modal Flow

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#299]
This is displayed when a user attempts to remove a single data object in a space

**Comment by michaelsena** [comment]
@oznekenzo, @oed reminded me that we can't remove data from a space unless it's open. So in the case that a user tries to remove a KV entry from a space that has not been opened, we likely need to add one modal step to our single-item deletion flow. See step 3 below:
<img width="1448" alt="Screen Shot 2019-03-12 at 9 14 58 PM" src="https://user-images.githubusercontent.com/5216274/54277869-59ad7a00-4567-11e9-8730-ac7daa7573a2.png">
In step 3, we would display this text and simultaneously ask the user to sign a consent message for the space in their web3 wallet. If they click cancel it takes them back to step 1 here (view item)
If the space is already open, then we can skip step 3

**Comment by oznekenzo** [comment]
@michaelsena - but you can't click on a datum from spaces unless its been opened to begin with?

**Comment by oznekenzo** [comment]
@michaelsena there is a bit of a weird UX in the situation where you have already signed for a space to open in the past so it doesn't trigger the Metamask modal - this results in a modal in the spaces UI pop up asking for consent for a fraction of a second after hitting delete.
I can think of a workaround / solution. If you have any ideas, would be happy to hear. Just thought I'd bring this up.
