### ISSUE TITLE
Improve Github/Twitter/Email verification flow

### ISSUE THREAD

**Issue by mattlockyer** [3box/3box-dapp#316]
### Description
Currently users experience failures when attempting to verify their twitter or github account because they input an incorrect format.

*We should make the following improvements:*
- [x] add static URL placeholder text before the input field. (i.e. github.com/[ ])
- [x] inside the [ ] we should add "username" as placeholder text that disappears when they begin typing
- [x] we should add a check that displays an error if incorrectly typed
- [x] we should only allow users to click the verify button if the entry is correctly formatted (i.e. no @ signs, etc)

**Comment by michaelsena** [comment]
We should also add a check which would throw an error in the UI alerting the user of their incorrect format.

**Comment by michaelsena** [comment]
Updated the description in the issue with the list of small improvements that will guarantee success.

**Comment by oznekenzo** [comment]
Great - let's get this thing over with!!
