### ISSUE TITLE
Support Threads Data Type in Management UI

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#330]
### How to Add `Thread` Data Type
This defines how we can add support for the data type `Thread` in our Data Management UI

#### Schema to ID a Thread
Key: "3box.thread.space-name.thread-name"

#### What to display
Threads will follow the `List` format of multiple entries.
* The first entry in the Thread List contains details of the Thread, including Thread Name
* Subsequent entries will display comments made by the user in that thread
* As of now threads (initial list item) and individual comments (subsequent entries) cannot be deleted

cc @oed

**Comment by oznekenzo** [comment]
thanks!
