### ISSUE TITLE
[PLACEHOLDER] Data Mgmt Desktop UI Cleanups

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#343]

**Comment by oznekenzo** [comment]
- [ ] sometimes loading spaces / list data fails, this should appear as an error in the UI and prompt a reload

**Comment by oznekenzo** [comment]
<img width="301" alt="Screen Shot 2019-03-28 at 12 19 47 PM" src="https://user-images.githubusercontent.com/8059373/55174449-d6d61300-5153-11e9-94e4-d139c562c858.png">
Key "Any" here, so it's a little confusing from the situation.  But still wondering if we can make things more clear by showing it as a code block like `this` ?

**Comment by oznekenzo** [comment]
Not great
<img width="519" alt="Screen Shot 2019-03-28 at 1 06 59 PM" src="https://user-images.githubusercontent.com/8059373/55177839-8910d900-515a-11e9-9731-a13a90226336.png">

**Comment by oznekenzo** [comment]
How to generally render objects in row / modal
<img width="1052" alt="Screen Shot 2019-03-28 at 1 08 46 PM" src="https://user-images.githubusercontent.com/8059373/55177888-a5ad1100-515a-11e9-854a-eb242f21c9a5.png">
{
 key: [value, value, value],
 key2: value2,
}

{
 key3: {
    key4: value4,
 }
}

**Comment by oznekenzo** [comment]
I have updated the above to show all the keys in the object in the content section
