### ISSUE TITLE
Add Spaces Data Tiles to Activity Feed

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#361]
### Implementation Notes
- update gray subtext on tile from “3Box Profile” to “SpaceName”. This is found directly under the user’s 3Box profile name. 
- use the same timestamp display logic as 3Box data tiles
- use the same grouping logic too based on space/store then timestamp
- for copy within the individual tiles, use “You saved a new entry: key.”
- display public space data by default, then if spaces are opened (during login or in the data explorer) also display private spaces data too
- when user clicks on a Spaces data item, open the data explorer page with a modal of that data open

**Comment by michaelsena** [comment]
added comments cc @oznekenzo

**Comment by oznekenzo** [comment]
- [ ] group feed items by space
- [ ] update activity feed after opening private space
