### ISSUE TITLE
Implement Team Page

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#370]
Desktop and mobile

**Comment by dazuck** [comment]
mine: 0xBcfD8dDAc6B8fe5144553B50790ca631b1760FB0

**Comment by michaelsena** [comment]
mine: 0xa8ee0babe72cd9a80ae45dd74cd3eae7a82fd5d1

**Comment by michaelsena** [comment]
@oznekenzo here's some feedback on the implementation at develop: Just saw and tested it on mobile. We should be displaying our names instead of hex addresses, on mobile (maybe on desktop too) the element is small, on mobile (maybe on desktop too) the element only opens when I click the image but should also show when I click the name, and on mobile when I click away it does not close. (I need to refresh the page.) - assuming you need to sync with @zachferland on how to make bigger and sub in names for hex addresses

**Comment by michaelsena** [comment]
@oznekenzo would be good to also open a new page to 3Box profiles if user clicks on profile tile on desktop.

This means: 
- on desktop: if user clicks member element it opens new page to profile (regardless if hover element is open or not)
- on mobile: keep current behavior: when users click the tile it displays the hover element, when they click away it closes

**Comment by dazuck** [comment]
@oznekenzo I'm getting a little too much credit on our current team page 

![image.png](https://images.zenhubusercontent.com/5b2d0d16ec017908afbeb74d/50e1ccce-ce3b-4322-86d4-cc6a8a8235ee)

**Comment by oznekenzo** [comment]
That’s a placeholder for holder who hasn’t given me his public ethereum
address

**Comment by michaelsena** [comment]
@oznekenzo I tested this on develop.3box.io and saw the line height was off in the new hover components. Maybe we have to update develop to the latest hover version to handle this bug?

After that works, we can probably push this page to master?

<img width="955" alt="Screen Shot 2019-06-04 at 5 04 31 PM" src="https://user-images.githubusercontent.com/5216274/58913807-03c21b80-86eb-11e9-8272-ca48be9eb3ec.png">

**Comment by michaelsena** [comment]
We should also update the functionality so that when users click on the tile, it opens our profile in a new page on desktop, and in the same page on mobile.

**Comment by oznekenzo** [comment]
@michaelsena The profile hover already opens a new tab, I think clicking on the tile on the page should just take you to that profile in the current window?

**Comment by michaelsena** [comment]
The problem with opening the profile on the same page is the profile load time, which is why opening in a new tab, if possible (everywhere except mobile web3 browsers where we would just disable clicking the tile), is preferred for now. Let's stick with that. cc @oznekenzo

**Comment by oznekenzo** [comment]
@michaelsena have implemented that behavior now.
But I don't follow the argument? We aren't linking to an outside page, which is when this UX pattern makes sense.  A slow profile load is experienced either way.  And the fact that opening in a new tab for each profile won't work on web3 seems like just another reason we shouldn't be opening in a new tab?

**Comment by oznekenzo** [comment]
@michaelsena also, are we linking to this page in the footer, in the nav or both?
That should be the last update.

**Comment by michaelsena** [comment]
> We aren't linking to an outside page, which is when this UX pattern makes sense.
This is actually a completely different application, and not really a part of the marketing site, so I would argue that it is a different app, just hosted on the same domain.

> are we linking to this page in the footer, in the nav or both?
Let's link in the footer

cc @oznekenzo
