### ISSUE TITLE
Polish pages for core release

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#390]

**Comment by oznekenzo** [comment]
- [ ] where does "more about 3box" redirect to?
- [ ] confusion: sign in to hub in nav & sign in to hub on app page have different func
- [ ] confusion: for users directs user to profile section on API pg for devs
- [ ] send "Join" form to same place as before?
- [ ] where does "About" page link to?

**Comment by michaelsena** [comment]
1. to the https://3box.io/about page, which we will implement next sprint
2. Let's update to "Log In" on App page
3. For Users meant to direct to App page
4. Where does "Join" go now? I imagined that was just an email submit with no redirect or anything.
5. About page will link to About page, which will be implemented next sprint: https://3box.io/about
6. Yup, it will open a new page to chat.3box.io
7. Yeah, would be great do you to design mollie's card and we can use that as the future design basis for the hover component. I like what you did on the first version. For content, let's also add to what you have now: description, emoji, ...
cc @oznekenzo
