### ISSUE TITLE
Implement followers on public profile pages

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#398]
- [x] Left align information in leftside profile menu
- [x] Check if following
- [x] "Add to Contacts"/"Added" button to public profile view (when logged in)
- [x] Prevent following if you already follow
- [x] Update follow state after fetching own profile
- [x] Mutual following & text
- [x] Display count & first 5 following
- [x] Display contact list modal on click
- [x] Check isFollowing for each user in following list modal
- [x] Follow user from following list modal and update state to remove button (or add unfollow button)
- [x] Place profile / data links in nav after signin
- [x] Bug in spaces after full login from follow
- [x] openBox after clicking follow results in unclosed states (separate isFetching MY activity & isFetching OTHERs activity)
- [x] Do not let "This is your public profile" banner persist after you leave page
- [x] Prevent yourself from following yourself
- [x] Profile hovers in contact tile
- [x] if no name, show address
- [x] Public profile margin w/ logged in Nav
- [x] Unfollow functionality
- [x] Create element for mutual contacts/add contact for logged out public profile view (see screenshot in comments)
- [x] State: address in local storage (following is loaded on public profile load, but not logged in, will show if user is following profile, will require login if user wants to unfollow / follow profile) [Cannot yet implement unfollow nor getThread by address]
- [x] State: unknown user (requires login to fetch mutual) [Cannot yet implement unfollow]
- [x] State: User logged in (Can follow and unfollow without any state change) [Cannot yet implement unfollow]
- [ ] Single empty contact (bug)

![Contacts - Public Profile](https://user-images.githubusercontent.com/5216274/57622532-d8b93180-755b-11e9-8ab6-f18765edfcb6.png)
![Contacts - Public Profile - Contact List](https://user-images.githubusercontent.com/5216274/57622771-4cf3d500-755c-11e9-911c-4e118ab492ff.png)

**Comment by michaelsena** [comment]
@oznekenzo this is ready to implement too. Same sketch file linked in Discord

**Comment by oznekenzo** [comment]
- [ ] when signed in, maintain signed in state when navigating to a public profile

**Comment by michaelsena** [comment]
Also, sign the user in if they're signed out and click `Add to Contacts`. Then after they're signed in display the correct button state (`Add to Contacts` or `Added`) and the rest of the correct contact detail

**Comment by oznekenzo** [comment]
@michaelsena, this will potentially take a user through an unexpected 5-30s of dapp loading time, do we want to add a prompt or warning to confirm a user wants to sign in?

**Comment by michaelsena** [comment]
Hm good question @oznekenzo - maybe let's try implementing without adding a modal, and if we test it and decide we need one, we can add one.

**Comment by michaelsena** [comment]
@oznekenzo I think we should display something like this for when a user is viewing a public profile when logged out. We can still see contact count/list, but cannot see contacts in common and can not add contact.

![Contacts Feature - Public Profile - Logged Out View](https://user-images.githubusercontent.com/5216274/57873605-b5e98000-77dc-11e9-81e6-871891134844.png)

**Comment by michaelsena** [comment]
@oznekenzo when you're ready here's the schema that we'll use to save entries to my following thread https://www.notion.so/threebox/Contacts-Data-Model-d8cef892b0b24a7494bdccad9dd44235

**Comment by oznekenzo** [comment]
@michaelsena in the schema you've attached above, the description written says "worked together", which likely has been input by the user who just followed the profile, though there is no UX/UI that handles this.  Do you want to add a modal after clicking "Follow" that will handle the input for this (and key "Name") ?

**Comment by oznekenzo** [comment]
This can be prepopulated by existing "Name" & "Description" values.
