### ISSUE TITLE
GET /  SET in Messaging Product Page

### ISSUE THREAD

**Issue by kuhnchris** [3box/3box-dapp#410]
**Describe the bug**
GET/SET Green box thingies look... not correct? Should they be placed over the actually API example?

**To Reproduce**
Go to "API Products" and "Messaging"

**Expected behavior**
API Example

**Screenshots**
![grafik](https://user-images.githubusercontent.com/761911/58384015-34b09b00-7fdd-11e9-99a8-ae7a8fbb903c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: latest stable

**Comment by kuhnchris** [comment]
is it supposed to look like this?
![grafik](https://user-images.githubusercontent.com/761911/58384285-4e071680-7fe0-11e9-9f39-5273029ea7e0.png)

**Comment by oznekenzo** [comment]
No, they should not be placed over the API example.  Thanks for fixing but
I worry you might run into the same problem I apparently had of it looking
different of different browsers (or whatever the initial problem was).
I’ll follow up with this.

**Comment by kuhnchris** [comment]
Apprently it looks broken on all of 'em:
http://browsershots.org/https://3box.io/products/profiles

The problem is that there is an absolute position in the styles.css.
In general I'd like to suggest a clean-up in the NewLandingPage, most stuff is measured in px, instead of "em", which makes compatibility not such easy across mobile devices.

But let me know, I'm up to help out if you need anythng.

**Comment by oznekenzo** [comment]
Sure, if you're able to do some work with cleaning some things up that you notice, we'd love the help
