### ISSUE TITLE
Basic implementation of Web3Connect

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#431]
Implement web3connect. With any questions, here's a link to their discord: https://discord.gg/mXJrhkG

- [ ] Implement web3connect, including any required refactor

**Comment by michaelsena** [comment]
Here is some code from the airswap team: https://github.com/airswap/AirSwap.js/blob/develop/src/wallet/redux/actions.js#L9

**Comment by michaelsena** [comment]
Here is a great general web3-react library that includes good code for supporting multiple providers: https://github.com/NoahZinsmeister/web3-react

**Comment by michaelsena** [comment]
Design example 1
<img width="1526" alt="Screen Shot 2019-06-18 at 2 41 47 PM" src="https://user-images.githubusercontent.com/5216274/59710615-46015780-91d7-11e9-9017-f62f9d169fd5.png">

**Comment by michaelsena** [comment]
Aaaand a good react component from the WalletConnect team: https://github.com/web3connect/web3connect

**Comment by oznekenzo** [comment]
- [ ] attach provider logouts to 3box log out button
- [ ] allow ethAddr change if from different web3 provider on login / switch addr modal only when with same web3 provider
- [ ] fortmatic error
