### ISSUE TITLE
Create Image for Twitter Profile Preview

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#436]

**Comment by michaelsena** [comment]
@oznekenzo I was thinking something like this. What are the twitter preview dimensions? Is there just one or multiple? And is it square or rectangle?
![Twitter Default Preview](https://user-images.githubusercontent.com/5216274/60558734-4130bd80-9d18-11e9-95d1-2b5621d193e5.png)

**Comment by oznekenzo** [comment]
Looks good!  I can come up with a few designs as well.

The one you did above would fit the app card [square]:
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/app-card

There is the smaller "Summary Card" we've been using [square]: 
![Screen Shot 2019-07-02 at 11 49 42 PM](https://user-images.githubusercontent.com/8059373/60562095-2106fb80-9d24-11e9-8bf3-0876e554ea75.png)

And the large one as seen on the medium posts you've been posting on our Twitter account (which is probably overkill for sharing a profile) [rectangle]:
![Screen Shot 2019-07-02 at 11 51 11 PM](https://user-images.githubusercontent.com/8059373/60562145-485dc880-9d24-11e9-8c1a-6609f1367517.png)
