### ISSUE TITLE
Migrate link preview configs and serverless function to master url

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-dapp#442]
Already set up on test url

**Comment by michaelsena** [comment]
@oznekenzo we can probably push this stuff to master now, and don't need to wait for the full Followers release. Thoughts?

**Comment by oznekenzo** [comment]
the master branch doesnt have the /previewRequest and /twitterRequest routes, so all link previews will render empty

**Comment by oznekenzo** [comment]
I can push those to master, using the old metatags, however, for the time being

**Comment by michaelsena** [comment]
will they render empty or no?

**Comment by oznekenzo** [comment]
if I push to master the two new routes above, they will render the static images and title tags.
Or I can implement the dynamic headers to master, without the follower feature.

**Comment by michaelsena** [comment]
Let's push whatever we can to master except for the followers feature because the two features are related, but not co-dependent.

Also should push the story to master to updating the twitter verification post message since its related to unfurling

**Comment by oznekenzo** [comment]
- [ ] merging dynamic headers in react helmet
- [ ] code splitting & other performance enhancements
- [ ]update twitter & github messages
- [ ] create prerender.io paid account
- [ ] testing
- [ ] point serverless functions to master url
