### ISSUE TITLE
Display current web3 provider in dropdown menu

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#444]
Display current wallet provider and allow user to "Change" to another. When clicked this button will open the web3connect selection modal.

On mobile (when web3 is injected - like status, coinbase wallet, trust, opera, etc) just hide the wallet piece, but continue to display network.

![network dropdown](https://user-images.githubusercontent.com/5216274/61254777-cc0bb200-a733-11e9-80c1-b089dff278fa.png)

**Comment by oznekenzo** [comment]
- [x] style
- [ ] functionality
