### ISSUE TITLE
Allow users to search for other users by ETH address

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#457]
### Problem
As a user of the 3Box Hub, there is no way for me to find other users inside of the app. I need to paste someones address into the URL bar to get to their profile if I don't follow them which isn't great UX.

### Solution
As a first version of search, we could add the ability for users to look up other users by searching their address in the dapp. Later, once we have indexing, we could evolve this into text search based on name or something.

**Comment by oznekenzo** [comment]
closing - done
