### ISSUE TITLE
Data sync issue on newly logged in accounts

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-dapp#460]
From discord:
kenzo: switching between providers or logging in to new accounts, were not getting that users data until we reload 3 times
kenzo: If I log in to fortmatic on my dtw browser, update info, then later login with fortmatic in the web2 broswer on my phone, I’m not going to see the info I just saved
Until I reload 3 times
And it seems to always be 3 times

oed: It could possibly be an issue where the HAS_ENTRIES response from the pinning-node doesn't get received for 3 secs which would trigger onSyncDone regardlessly. 
That't might possibly happen if the store takes a long time to load on the pinning-node maybe because of heavy cpu usage.

**Comment by zachferland** [comment]
Link - https://github.com/3box/3box-js/issues/539

**Comment by oznekenzo** [comment]
This has improved to loading required only once before data is correctly synced.

Also has been recorded that `onSyncDone` is not getting called in the dapp, regardless of number of dapp loads.

**Comment by oznekenzo** [comment]
moving to .then syntax for open box, onSyncDone throws the error 
`Uncaught (in promise) TypeError: _this._onSyncDoneCB is not a function
    at _callee2$ (3box.js:384)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:264)
    at Generator.prototype.<computed> [as next] (runtime.js:98)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)`

**Comment by oed** [comment]
Well it looks like the function you pass to `onSyncDone` is not a function. Can you link the code where this happens?
