### ISSUE TITLE
Test Following feature, now with w3c

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-dapp#462]
- [x] Loading animation in follow button in modal is unmodified
- [x] When clicking Follow while other buttons are in the process
- [x] Following tab loading animation
- [x] Switching account (mm to fortmatic) did not reset myprofile values - not with "Change wallet" but logging in again with "Choose"
- [x] "No previous account saved" when it recognizes that Im on my public profile page
- [x] "Your profile" margin remains when redirecting to non-public profile page
- [x] Don't let following in profile wait for activity
- [x] Following from pub profile on logged out state not working with fortmatic
- [x] Following working with MM
- [x] Following working with Fortmatic
- [x] Following working with Portis
- [x] Test with multiple tabs open

**Comment by oznekenzo** [comment]
- [ ] Following working with WalletConnect
- [ ] Following join thread bug prevents MM working on first time, and always for Walletconnect
- [ ] following is public is showing up multiple time
- [ ] unfollow when youve already unfollowed from another tab, what would happen? dont do the inverse
- [ ] remove word "Foloowing" from mutual
- [ ] make border the background grey but keep white on modal

**Comment by michaelsena** [comment]
closing this issue and opening a new one for the upcoming sprint
