### ISSUE TITLE
Verifications not working in Firefox/Chrome browsers

### ISSUE THREAD

**Issue by santospirito** [3box/3box-dapp#469]
**Describe the bug**
Attempting to verify one's Twitter or email address is not working. While 3Box is displaying the steps to verify and generating the necessary Tweets/codes, the actual verification of a received code fails. This is failing in both Firefox and Chrome browsers.

**To Reproduce**
Steps to reproduce the behavior for Twitter:
1. Edit details of the 3Box profile.
2. Enter Twitter handle without the '@' symbol.
3. Tweet the unique verification key.
4. Click the "Verify" button.
5. Fails to verify.

Steps to reproduce the behavior for email:
1. Edit details of the 3Box profile.
2. Enter email address.
3. Send verification code to email address.
4. Enter received verification code into the text field and click "Verify" button.
5. Fails to verify.

**Expected behavior**
For email verification - after receiving the code and inputting it in the text field, the email should successfully verify. For Twitter verification - after posting the Tweet, the verification should complete successfully.

**Screenshots**
<img width="807" alt="Screen Shot 2019-08-14 at 11 18 45 AM" src="https://user-images.githubusercontent.com/33099734/63033726-16dd2e80-be86-11e9-9d5f-97c7e0e12589.png">
<img width="805" alt="Screen Shot 2019-08-14 at 11 20 04 AM" src="https://user-images.githubusercontent.com/33099734/63033728-16dd2e80-be86-11e9-93c2-de994b949a90.png">

**Desktop (please complete the following information):**
 - OS: macOS Mojave version 10.14.6
 - Browser: Google Chrome and Firefox
 - Version: Google Chrome version 76.0.3809.100 (Official Build) (64-bit); Firefox Quantum 68.0.2 (64-bit)

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version : N/A

**Comment by oed** [comment]
@oznekenzo have you got a chance to look at this? Where you able to replicate it?

**Comment by oznekenzo** [comment]
Old - closing

**Comment by oznekenzo** [comment]
@santospirito pardon my bed-side manner! Are you still this issue @santospirito ?

**Comment by santospirito** [comment]
@oznekenzo my bad, I spaced this too! I've just tested and everything is working as expected. Thanks!
