### ISSUE TITLE
Implement basic user search flow

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#490]

**Comment by oznekenzo** [comment]
SEARCH BAR

search bar with filler text indicating current abilities (Search by 0x address...)
RESULTS DROPDOWN

after complete address is entered, display profile result in a dropdown that shows profile information (image, name, emoji, perhaps twitter and github)
if address is incomplete (not enough characters), display message indicating so
if no profile exists, display message indicating so
... anything missing?
