### ISSUE TITLE
Optimize profile commenting flows

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#494]
Based on feedback from @michaelsena

**Comment by oznekenzo** [comment]
- [ ] Disabled wall empty state / messaging + image
- [ ] Enabled wall empty state - describing the feature "This is your profile wall, a place where to share updates and for others to leave messages"
- [ ] Disabled on page but that state is saved in localstate not redux
- [ ] If wall is disabled on public profile, just remove the wall option
- [ ] API Products is bold when its not active, should just be full color
- [ ] unify loading animations
- [ ] wall is showing when it shouldnt
- [ ] input ui profile picture needs a white background
- [ ] Taking long time to fetch wall - see if its bc of the front end
- [ ] Links not rendering like other text - make it blue also
- [ ] Link unfurling on the wall?
- [ ] Following section on mobile font is weird
- [ ] Unify tab content on mobile
- [ ] Mobile header is above hover on sqeezed dtw state
- [ ] Mobile profile description should be centered
