### ISSUE TITLE
Enable Authereum as provider in W3C

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#502]

**Comment by oznekenzo** [comment]
Am getting this error which is preventing me from using Authereum to login:
<img width="582" alt="Screen Shot 2019-11-11 at 2 28 17 PM" src="https://user-images.githubusercontent.com/8059373/68614841-bfa02780-048f-11ea-8796-22326bc72219.png">

**Comment by oznekenzo** [comment]
Blocked by this newer issue atm:
https://github.com/3box/identity-wallet-js/issues/22

**Comment by oznekenzo** [comment]
Looked further into it, the authereum provider returns your account in a different way (ugh) than other providers from the `getAccounts` method - fixed this but a second issue where Web3Connect returns 'MetaMask' as the name of the wallet when using 'Authereum' as a provider is messing with our setting of the default wallet.  I created an issue in web3connect and hopefully pedro or someone else can make a quick fix for this.

**Comment by michaelsena** [comment]
@oznekenzo have you checked in with @crisgarner on this?

**Comment by oznekenzo** [comment]
Here's the issue: https://github.com/web3connect/web3connect/issues/98
Pinged cris and pedro for a response
