### ISSUE TITLE
Update partners page

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#504]
Applications
- [x] Alethio
- [x] Zerion
- [x] MolochDAO (activate link)
- [ ] ~Esence~
- [x] DAOstack (coming soon)
- [x] Gnosis (which product is this?) (coming soon)
- [x] Rarible (coming soon)
- [x] SuperRare (coming soon)
- [ ] ~hustla's app~
- [x] microsponsors (coming soon)
- [ ] ~Rapid (???)~
- [ ] ~Enable (enable.credit) use 3Box yet?~
- [x] ETHDenver DAO (coming soon)
- [x] Livepeer (coming soon)
- [ ] ~Roundabout (https://roundabout.exchange)~

Wallets/Browsers
- [x] MetaMask (activate link)
- [x] Authereum (https://authereum.org)
- [x] Fortmatic (coming soon)
- [x] Portis (coming soon)
- [x] Pillar (coming soon)
- [ ] ~EID (in development, visit Github)~
- [x] Alice (coming soon)
- [x] Fuse 
- [ ] ~Yup (coming soon)~

Dev Tools
- [ ] Remix
- [ ] SimpleID (coming soon)
- [ ] DappKit (coming soon)
- [ ] ~Extensions (in development, visit Github)~

**Comment by dazuck** [comment]
are we shelving this page update for the time being? If so, can we just change the form link to an email to partners@3box.io so we get updates on new ones (have had a few go into the form void i think)
