### ISSUE TITLE
Display ENS names throughout My Profile page

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#541]
- [x] on my wall and activity feed - if a user has a 3Box profile, display it next to or under the 3Box name; if a user doesn't have a profile, then replace the Hex with the ENS name
- [x] under my name on the sidebar
- [x] move Ethereum address our of sidebar, to above the activity feed and collectibles

**Comment by oznekenzo** [comment]
network color corresponds

**Comment by oznekenzo** [comment]
left align proifle sidebar

**Comment by oznekenzo** [comment]
and wall
