### ISSUE TITLE
Display ENS names throughout Public Profile page

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-dapp#542]
- [x] Under my name on sidebar
- [x] on wall
- [x] on activity feed

**Comment by oznekenzo** [comment]
@michaelsena the ens name should only show in one place at a time on your public profile no? so just on the side bar, not on wall or activity feed

**Comment by oznekenzo** [comment]
Use blockies in Search result dropdown

**Comment by oznekenzo** [comment]
Pass ethereum address, not ens to route for onclick

**Comment by oznekenzo** [comment]
"3id.eth is not a valid ens name"
