### ISSUE TITLE
Sign up for paid version of CircleCI

### ISSUE THREAD

**Issue by oznekenzo** [3box/3box-dapp#592]
The paid version allows for more max memory, the lack of which fails the build process and we can't automatically deploy.  For a sprint now, I have been manually deploying

**Comment by zachferland** [comment]
will it not work now that you fixed the plugins ?

**Comment by oznekenzo** [comment]
No it still maxes out

**Comment by dazuck** [comment]
signed up for the cheapest paid version. let me know if something else is needed
